name: ecopoints
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  form_field_validator: ^1.1.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
